export const caseStudies = [
  {
    id: 1,
    client: 'Rakuten',
    year: 2023,
    market: 'US',
    title: 'TikTok Creative Optimization',
    industry: ['retail', 'e-commerce', 'shopping', 'marketplace'],
    challenges: ['improving efficiency', 'creative performance', 'user acquisition'],
    channels: ['paid social', 'tiktok', 'influencers'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'creative effectiveness', 'channel expertise', 'test & learn'],
    tags: ['shopping rewards', 'spark ads', 'app installs'],
    result: '-35% CPI, -31% CPA, +77% SKAN click conversion rate',
    summary: 'Used TikTok Creative Exchange and Automatic Creative Optimization to test 40+ permutations and find the best-performing creative mix.',
    relevanceHook: 'Strong proof for paid social, creator-led acquisition, and performance creative testing.',
    competitors: ['Honey', 'Ibotta', 'Fetch Rewards', 'Capital One Shopping'],
    synonyms: ['TikTok Ads', 'Cashback', 'Rewards', 'Affiliate', 'Creator Ads'],
    story: "Rakuten wanted TikTok to work like a serious acquisition channel, not just a place to post brand creative. We brought in TikTok Creative Exchange partners and fed more than 40 creative combinations through Automatic Creative Optimization. That testing discipline helped us find the mix that actually converted, cutting CPA by 34% while lifting installs and purchase rates.",
  },
  {
    id: 2,
    client: 'SoundCloud',
    year: 2022,
    market: 'US',
    title: 'YouTube Acquisition Optimization',
    industry: ['streaming', 'audio', 'subscription', 'entertainment'],
    challenges: ['improving efficiency', 'fixing measurement', 'user acquisition'],
    channels: ['youtube', 'ctv', 'programmatic'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'measurement & attribution', 'audience strategy', 'channel expertise'],
    tags: ['retargeting', 'lookalikes', 'artist acquisition'],
    result: '-82% acquisition costs, -45% CPV, 9% under CPA goal',
    summary: 'Fixed broken measurement, rebuilt audience strategy, and improved creative mix to turn YouTube into the most efficient acquisition channel.',
    relevanceHook: 'Excellent proof for measurement cleanup and turning around an underperforming channel.',
    competitors: ['Spotify', 'Apple Music', 'Tidal', 'Pandora'],
    synonyms: ['Video Ads', 'Google Ads', 'Music', 'Artists'],
    story: "SoundCloud had a YouTube acquisition problem: the channel was spending, but it was underdelivering. We found gaps in tracking, rebuilt their retargeting structure, and refreshed the creative so the system had better inputs. That reset turned YouTube into their most efficient acquisition channel and brought CPA in 9% under target.",
  },
  {
    id: 3,
    client: 'SoundCloud',
    year: 2022,
    market: 'US',
    title: 'TikTok Influencer User Acquisition',
    industry: ['streaming', 'audio', 'subscription', 'entertainment'],
    challenges: ['user acquisition', 'creative performance', 'improving efficiency'],
    channels: ['paid social', 'tiktok', 'influencers'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'channel expertise', 'creative effectiveness'],
    tags: ['spark ads', 'creator content', 'app installs'],
    result: 'Lowest CPA in SoundCloud TikTok history',
    summary: 'Used artist-led creator content and Spark Ads to build authentic TikTok-native acquisition that outperformed prior benchmarks.',
    relevanceHook: 'Great for creator-led social, TikTok-native thinking, and efficient subscription growth.',
    competitors: ['Spotify', 'Apple Music', 'Tidal', 'Pandora'],
    story: "SoundCloud needed TikTok acquisition to feel native, not like recycled ad creative. We worked with artists and creator-led content, then amplified the strongest assets through Spark Ads. Because the work felt native to the platform, it drove the lowest CPA SoundCloud had seen on TikTok.",
    synonyms: ['TikTok Ads', 'Creator UA', 'Music', 'Artists', 'UGC'],
  },
  {
    id: 4,
    client: 'Local Now',
    year: 2021,
    market: 'US',
    title: 'App Store Optimization',
    industry: ['streaming', 'media', 'avod', 'news'],
    challenges: ['growing organic acquisition', 'discoverability', 'improving efficiency'],
    channels: ['aso'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'channel expertise', 'test & learn'],
    tags: ['Google Play', 'organic', 'keywords'],
    result: '+80% Top 10 keywords, +4% conversion lift, +35% organic downloads',
    summary: 'Overhauled Google Play keyword strategy, title, and short description to improve discoverability and conversion.',
    relevanceHook: 'Clean proof for ASO and organic app growth.',
    competitors: ['Pluto TV', 'Tubi', 'Peacock', 'NewsBreak', 'Dave', 'Dave.com', 'Chime', 'Current'],
    synonyms: ['Google Play', 'organic acquisition', 'aso', 'App Store Optimization', 'dave', 'dave.com'],
    story: 'Local Now needed to improve how efficiently it captured organic app demand. We overhauled the Google Play listing strategy—keywords, title, and description—to better match what users were actually searching for. That drove stronger keyword rankings and a meaningful lift in organic downloads.',
  },
  {
    id: 5,
    client: 'FanDuel',
    year: 2020,
    market: 'US',
    title: 'Reddit Creative Testing',
    industry: ['gaming', 'sports betting', 'finance', 'entertainment'],
    challenges: ['creative performance', 'channel-native creative', 'improving efficiency'],
    channels: ['paid social', 'reddit'],
    regions: ['americas'],
    outcomeTypes: ['creative effectiveness', 'channel expertise', 'test & learn'],
    tags: ['meme creative', 'regulated gaming'],
    result: '+17% higher conversion vs control',
    summary: 'Created Reddit-native meme-based ad variants that outperformed standard branded creative across the channel.',
    relevanceHook: 'Best for channel-native creative thinking and social platform adaptation.',
    competitors: ['DraftKings', 'BetMGM', 'Caesars Sportsbook'],
    story: "FanDuel wanted to crack Reddit, but standard display ads weren't converting. We built meme-inspired creative variants specifically designed for how Redditors communicate. By speaking the platform's language instead of forcing a standard brand ad, the native concepts outperformed the control group by 17%.",
    synonyms: ['paid social', 'Facebook Ads', 'Instagram Ads'],
  },
  {
    id: 6,
    client: 'Pokémon GO',
    year: 2020,
    market: 'US',
    title: 'Full Funnel Campaign',
    industry: ['gaming', 'mobile', 'entertainment'],
    challenges: ['launching in new market', 'full-funnel growth', 'user acquisition'],
    channels: ['ctv', 'dooh', 'paid social', 'programmatic', 'paid search'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'channel expertise', 'audience strategy', 'test & learn'],
    tags: ['instagram', 'facebook', 'Google App Campaigns'],
    result: 'Significant DAU and new user uplift',
    summary: 'Built a full-funnel launch campaign using CTV, DOOH, paid social, and retargeting to drive awareness and new user growth.',
    relevanceHook: 'Strong example for multi-channel launch orchestration.',
    competitors: ['Niantic titles', 'Harry Potter: Wizards Unite'],
    story: "When Pokémon GO needed a massive acquisition push, we orchestrated a true full-funnel approach. We used CTV and digital out-of-home in specific markets to build awareness, then captured that intent with targeted social and programmatic ads. That coordinated layering drove significant lifts in both new users and daily active players.",
    synonyms: ['Meta UA', 'Facebook Ads', 'Instagram Ads'],
  },
  {
    id: 7,
    client: 'Neou Fitness',
    year: 2020,
    market: 'US / CA / UK / AU',
    title: 'Creative Effectiveness & User Acquisition',
    industry: ['fitness', 'health & wellness', 'subscription'],
    challenges: ['user acquisition', 'creative performance', 'launching in new market'],
    channels: ['paid social', 'paid search'],
    regions: ['americas', 'emea'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'creative effectiveness', 'test & learn'],
    tags: ['international expansion', 'a/b testing'],
    result: '+48% subscriptions, -122% cost per subscription',
    summary: 'A/B tested static and video creative, then scaled winning concepts internationally across multiple markets.',
    relevanceHook: 'Great proof for fitness subscription growth and creative iteration at scale.',
    competitors: ['Peloton', 'Nike Training Club', 'Daily Burn'],
    story: "Neou Fitness needed to scale subscriptions fast. We started by aggressively A/B testing static and video creative on paid social to find out exactly what resonated. Once we had a winning template, we scaled those proven concepts internationally across the US, Canada, the UK, and Australia, dropping their cost per subscription by over 120% in five months.",
    synonyms: ['Meta UA', 'meta user acquisition', 'Paid Social UA', 'Facebook Ads', 'Instagram Ads'],
  },
  {
    id: 8,
    client: 'Amazon Shopping',
    year: 2020,
    market: 'US',
    title: 'Ad Fraud Protection',
    industry: ['retail', 'e-commerce', 'shopping', 'marketplace'],
    challenges: ['improving efficiency', 'fraud reduction', 'measurement cleanup'],
    channels: ['programmatic', 'display'],
    regions: ['americas'],
    outcomeTypes: ['fraud & brand safety', 'cost efficiency', 'measurement & attribution'],
    tags: ['ad fraud', 'in-app display'],
    result: '+176% monthly install volume, $1.4M fraud savings, -31% fraud rate',
    summary: 'Implemented fraud monitoring and source blacklisting across programmatic placements to protect spend and improve quality.',
    relevanceHook: 'Best example for fraud reduction, media quality control, and performance protection.',
    competitors: ['Walmart', 'Target', 'eBay', 'Instacart'],
    story: "Amazon Shopping was spending heavily on programmatic, but we needed to ensure that budget was driving real installs, not just funding ad fraud. We partnered with a third-party monitor, built strict prevention rules, and proactively blacklisted high-fraud sources on a weekly basis. That active defense cut their fraud rate by 31% and saved them $1.4 million.",
    synonyms: [],
  },
  {
    id: 9,
    client: 'Amazon Shopping',
    year: 2020,
    market: 'US',
    title: 'Creative Testing & Programmatic',
    industry: ['retail', 'e-commerce', 'shopping', 'marketplace'],
    challenges: ['creative performance', 'improving efficiency', 'conversion improvement'],
    channels: ['programmatic', 'display'],
    regions: ['americas'],
    outcomeTypes: ['creative effectiveness', 'cost efficiency', 'test & learn'],
    tags: ['cta testing', 'creative testing'],
    result: '+176% iOS CTR, +54% Android conversion rate, +27% iOS conversion rate',
    summary: 'Ran sequential CTA and creative-theme tests across programmatic display to identify the strongest-performing combinations.',
    relevanceHook: 'Strong proof for disciplined creative testing in lower-funnel media.',
    competitors: ['Walmart', 'Target', 'eBay', 'Instacart'],
    story: "Amazon Shopping needed to know whether programmatic was truly driving new growth or just taking credit for users who would have converted anyway. We set up an exposed-versus-control test through DSPs and measured the lift over a 30-day window. The result gave them hard proof that the channel was incremental and worth scaling.",
    synonyms: [],
  },
  {
    id: 10,
    client: 'Amazon Shopping',
    year: 2020,
    market: 'US',
    title: 'Incrementality Testing',
    industry: ['retail', 'e-commerce', 'shopping', 'marketplace'],
    challenges: ['fixing measurement', 'incrementality', 'user acquisition'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['measurement & attribution', 'scale & growth', 'test & learn'],
    tags: ['DSP', 'incrementality'],
    result: '+130% Android conversion rate, >80% overall lift',
    summary: 'Built exposed vs control experiments to validate incremental value from programmatic media with statistical rigor.',
    relevanceHook: 'Best proof point for measurement maturity and incrementality validation.',
    competitors: ['Walmart', 'Target', 'eBay', 'Instacart'],
    story: "Amazon Shopping needed to know whether programmatic was truly driving new growth or just taking credit for users who would have converted anyway. We set up an exposed-versus-control test through DSPs and measured the lift over a 30-day window. The result gave them hard proof that the channel was incremental and worth scaling.",
    synonyms: [],
  },
  {
    id: 11,
    client: 'Audible',
    year: 2020,
    market: 'Canada',
    title: 'Audience Engagement via Custom Content',
    industry: ['audio', 'publishing', 'subscription', 'entertainment'],
    challenges: ['brand awareness', 'audience engagement', 'content-led growth'],
    channels: ['programmatic', 'display', 'content'],
    regions: ['americas'],
    outcomeTypes: ['creative effectiveness', 'audience strategy', 'scale & growth'],
    tags: ['custom content', 'high-impact display'],
    result: '18x higher content engagement, 2x higher CTR',
    summary: 'Used editorial content and high-impact placements to drive stronger engagement and consideration for Audible.',
    relevanceHook: 'Useful for upper-funnel brand work with editorial storytelling.',
    competitors: ['Spotify', 'Libro.fm', 'Apple Books'],
    story: "Audible wanted to capture upper-funnel attention during the pandemic by giving people a reason to engage, not just an ad to click. We partnered with premium publishers to create co-branded listicles and quizzes, and paired them with high-impact spotlight ads. That editorial approach drove 18 times more engagement than standard banners.",
    synonyms: [],
  },
  {
    id: 12,
    client: 'Audible',
    year: 2020,
    market: 'Canada',
    title: 'Incrementality Testing via Google App Campaigns',
    industry: ['audio', 'publishing', 'subscription', 'entertainment'],
    challenges: ['fixing measurement', 'user acquisition', 'improving efficiency'],
    channels: ['paid search', 'Google App Campaigns'],
    regions: ['americas'],
    outcomeTypes: ['measurement & attribution', 'cost efficiency', 'test & learn'],
    tags: ['geo split', 'incrementality'],
    result: '+17% incremental uplift in trials, +15% improved cost per trial',
    summary: 'Used randomized geo holdouts to measure true incremental trial lift from Google App Campaigns.',
    relevanceHook: 'Strong proof for rigorous channel validation and cost discipline.',
    competitors: ['Spotify', 'Libro.fm', 'Apple Books'],
    story: "Audible wanted a cleaner answer on whether Google App Campaigns were really moving the business. Rather than rely on platform reporting, we built a geo-holdout test across Canadian markets to isolate true incremental impact. That gave them a more credible read on performance and showed a 17% lift in trial starts.",
    synonyms: [],
  },
  {
    id: 13,
    client: 'Boston Globe',
    year: 2020,
    market: 'US',
    title: 'Creative & Landing Page Testing',
    industry: ['media', 'news', 'publishing', 'subscription'],
    challenges: ['improving efficiency', 'creative performance', 'conversion improvement'],
    channels: ['paid social', 'native'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'creative effectiveness', 'test & learn', 'audience strategy'],
    tags: ['landing page testing', 'subscription acquisition'],
    result: '45% improvement in cost per subscription',
    summary: 'Matched channel-specific creative and landing page strategies to reduce cost per subscription across paid social and native.',
    relevanceHook: 'Best for subscription conversion and landing page optimization proof.',
    competitors: ['NYT', 'Washington Post', 'The Atlantic'],
    story: "The Boston Globe needed to acquire digital subscribers more efficiently. We realized that users from native ads wanted content, while users from paid social were looking for a deal. By matching the landing page experience—content-led versus offer-led—to the traffic source, we removed friction and dropped the cost per subscription by 45%.",
    synonyms: [],
  },
  {
    id: 14,
    client: 'ComiXology',
    year: 2020,
    market: 'US',
    title: 'Landing Page Testing',
    industry: ['entertainment', 'e-commerce', 'digital media'],
    challenges: ['conversion improvement', 'improving efficiency', 'driving revenue'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'creative effectiveness', 'test & learn'],
    tags: ['landing page', 'digital marketplace'],
    result: '-22% cost per purchase, +74% purchases, +42% revenue',
    summary: 'A/B tested alternative landing page sale formats to reduce friction and increase purchase volume.',
    relevanceHook: 'Strong example for e-commerce post-click optimization.',
    competitors: ['Marvel Unlimited', 'DC Universe Infinite'],
    story: "For ComiXology, we knew getting a click wasn't enough if the landing page didn't convert. We A/B tested a focused 6-comic preview against a sprawling 30-comic layout. It turned out the cleaner, shorter page reduced decision fatigue and drove significantly higher purchase rates, boosting revenue by 42% while lowering costs.",
    synonyms: [],
  },
  {
    id: 15,
    client: 'Pinna',
    year: 2020,
    market: 'US',
    title: 'Native vs. Display User Acquisition',
    industry: ['audio', 'kids', 'family', 'subscription'],
    challenges: ['user acquisition', 'improving efficiency', 'brand awareness'],
    channels: ['programmatic', 'display', 'native'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'test & learn', 'audience strategy', 'channel expertise'],
    tags: ['storygize', 'gdn'],
    result: 'Native: 8x more efficient CPT. Display: 41% higher CTR',
    summary: 'Compared native and dynamic display by funnel stage to understand the right job for each channel.',
    relevanceHook: 'Useful proof for channel-role clarity and family subscription growth.',
    competitors: ['Spotify Kids', 'Amazon Kids+', 'Audible'],
    story: "Pinna needed to figure out how to best use native and display ads for their family audio app. By running them side by side, we proved they did completely different jobs: display was great for cheap, upper-funnel reach and consideration, while native drove actual trial conversions eight times more efficiently. That clarity let us optimize the budget for the whole funnel.",
    synonyms: [],
  },
  {
    id: 16,
    client: 'Groupon',
    year: 2026,
    market: 'US, EMEA',
    title: 'AI-Powered Brand Creative',
    industry: ['retail', 'e-commerce', 'marketplace'],
    challenges: ['brand repositioning', 'scaling awareness', 'creative performance'],
    channels: ['youtube', 'ctv', 'ott', 'programmatic'],
    regions: ['americas', 'emea'],
    outcomeTypes: ['creative effectiveness', 'scale & growth', 'test & learn'],
    tags: ['ai creative', 'localization', 'brand reactivation'],
    result: '+11% Search Lift, +22% Brand Salience, +31% Unaided Ad Recall',
    summary: 'Built a human-directed, AI-enabled production model to create multi-market brand creative faster and more efficiently.',
    relevanceHook: 'High-impact CEO-friendly proof for modern creative production and brand lift.',
    competitors: ['LivingSocial', 'Viator', 'GetYourGuide'],
    synonyms: ['meta', 'Facebook Ads', 'Instagram Ads'],
    story: "Groupon needed to move faster across multiple cities without getting trapped in a slow, expensive production cycle. We used AI as a speed layer for storyboard development and localization, while keeping strong human direction over the final work. That let the team bring campaign-ready creative to market far faster and drove a 31% lift in unaided ad recall.",
  },
  {
    id: 17,
    client: 'Canva',
    year: 2026,
    market: 'India',
    title: 'Incremental Reach via OTT & Audio',
    industry: ['saas', 'software', 'productivity'],
    challenges: ['launching in new market', 'scaling reach', 'brand awareness'],
    channels: ['programmatic', 'ott', 'ctv', 'audio'],
    regions: ['apac'],
    outcomeTypes: ['scale & growth', 'audience strategy', 'measurement & attribution'],
    tags: ['india', 'incremental reach'],
    result: '300M+ impressions, 80M unique viewers, 60% incremental reach in Month 2',
    summary: 'Layered OTT and audio strategically to create broad but efficient brand reach across India with low audience overlap.',
    relevanceHook: 'Excellent proof for emerging-market reach and cross-channel brand planning.',
    competitors: ['Adobe Express', 'Microsoft Designer', 'Figma', 'Dave', 'Dave.com', 'Chime', 'Current'],
    synonyms: ['meta', 'Facebook Ads', 'Instagram Ads', 'ctv', 'ott', 'dave', 'dave.com'],
    story: 'Canva wanted to scale brand reach in India without wasting spend on overlapping audiences. We combined OTT and audio in a complementary way so each channel expanded reach instead of duplicating it. That gave them massive scale and strong incremental reach very quickly.',
  },
  {
    id: 18,
    client: 'Headspace',
    year: 2025,
    market: 'US',
    title: 'Custom Store Listings for Sleep',
    industry: ['health & wellness', 'fitness', 'subscription'],
    challenges: ['improving efficiency', 'growing organic acquisition', 'positioning by need-state'],
    channels: ['aso'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'channel expertise', 'test & learn'],
    tags: ['Sleep Week', 'Google Play'],
    result: '+31% sleep-related visitors, +49% acquisitions, +26% CVR',
    summary: 'Created a sleep-themed Custom Store Listing to win higher-intent wellness traffic and improve store conversion.',
    relevanceHook: 'Clean proof for ASO, category-specific acquisition, and health app growth.',
    competitors: ['Calm', 'Ten Percent Happier', 'Insight Timer'],
    synonyms: ['Meta UA', 'meta user acquisition', 'Paid Social UA', 'Facebook Ads', 'Instagram Ads'],
    story: "Headspace wanted to capture people already searching for sleep support, not just drive generic store traffic. We built a sleep-focused Custom Store Listing around Sleep Week, aligning keywords, screenshots, and visual cues to that specific use case. That tighter message-to-store fit lifted acquisitions by 49% and improved conversion rate by 26%.",
  },
  {
    id: 19,
    client: 'Maya Bank',
    year: 2025,
    market: 'Philippines',
    title: 'ASO Custom Store Listings',
    industry: ['finance', 'fintech', 'banking'],
    challenges: ['improving efficiency', 'category conversion', 'keyword targeting'],
    channels: ['aso'],
    regions: ['apac'],
    outcomeTypes: ['scale & growth', 'channel expertise', 'test & learn'],
    tags: ['lending', 'Google Play'],
    result: '+31% new-user CVR, +22% reinstall CVR, +106% top keyword CVR',
    summary: 'Built lending-specific Custom Store Listings to improve high-intent conversion for a digital banking product.',
    relevanceHook: 'Best fit for fintech, lending, and ASO-led conversion improvement.',
    competitors: ['GCash', 'PayMaya', 'Tonik', 'SeaBank', 'Dave', 'Dave.com', 'Chime', 'Current', 'Albert'],
    synonyms: ['Google Play', 'organic acquisition', 'dave', 'dave.com', 'Consumer Fintech', 'Neobank'],
    story: 'Maya Bank needed to improve conversion for high-intent lending users in the Philippines. We built lending-specific Custom Store Listings so people searching for exactly those solutions saw a much more relevant store experience. That sharper alignment lifted new-user conversion by 31% and more than doubled top-keyword conversion.',
  },
  {
    id: 20,
    client: 'Rodd & Gunn',
    year: 2025,
    market: 'North America',
    title: 'Loyalty Day Flash Sale',
    industry: ['fashion', 'retail', 'dtc', 'e-commerce'],
    challenges: ['retention', 'driving revenue', 'improving efficiency'],
    channels: ['paid social', 'paid search'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'audience strategy', 'creative effectiveness'],
    tags: ['lead generation', 'flash sale', 'loyalty'],
    result: '+500% purchases, +556% revenue, +56.6% ROAS',
    summary: 'Used a two-phase Meta and SEM program to grow loyalty membership, then monetize it through a highly targeted flash sale.',
    relevanceHook: 'Very strong proof for DTC retention and monetization.',
    competitors: ['Ralph Lauren', 'Brooks Brothers', 'Peter Millar'],
    synonyms: ['meta', 'Facebook Ads', 'Instagram Ads', 'paid social'],
    story: "Rodd & Gunn wanted loyalty to behave like a revenue engine, not just a retention program. We first used Meta lead ads to build the member base, then followed with a tightly timed 30-hour flash sale aimed squarely at conversion. The two-phase structure helped turn audience growth into immediate commercial return, driving a 500% jump in purchases.",
  },
  {
    id: 21,
    client: 'TickPick',
    year: 2024,
    market: 'US',
    title: 'Full-Funnel Programmatic',
    industry: ['entertainment', 'ticketing', 'marketplace', 'sports'],
    challenges: ['improving efficiency', 'scaling reach', 'full-funnel growth'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'audience strategy'],
    tags: ['DSP', 'prospecting', 'retargeting'],
    result: '+65% improved CPA, 22M+ unique users reached',
    summary: 'Built a three-month programmatic strategy balancing prospecting and retargeting to move users through the ticket-buying journey.',
    relevanceHook: 'Great for marketplace growth and lower-funnel programmatic proof.',
    competitors: ['StubHub', 'SeatGeek', 'Ticketmaster', 'Vivid Seats'],
    synonyms: [],
    story: "TickPick needed to grow ticket sales without losing efficiency. We split the programmatic plan into two clear jobs: prospecting to bring the right people into the funnel, and retargeting to convert them with sharper no-fee messaging. That structure let us scale reach materially while improving CPA by 65%.",
  },
  {
    id: 22,
    client: 'TickPick',
    year: 2024,
    market: 'US',
    title: 'Podcast Brand Awareness',
    industry: ['entertainment', 'ticketing', 'marketplace', 'sports'],
    challenges: ['brand awareness', 'scaling reach', 'measurement'],
    channels: ['audio', 'podcast'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'measurement & attribution', 'channel expertise'],
    tags: ['host-read', 'brand lift'],
    result: '+20PPT brand awareness, +117% purchases, +144% ROAS',
    summary: 'Ran host-read podcast campaigns across sports and entertainment shows and validated performance with a brand lift study.',
    relevanceHook: 'Strong proof for audio and brand lift with real commercial outcomes.',
    competitors: ['StubHub', 'SeatGeek', 'Ticketmaster', 'Vivid Seats'],
    story: "TickPick wanted to use audio to challenge much larger ticketing competitors. We built the plan around host-read placements in sports and entertainment podcasts, then optimized the mix based on which shows were actually driving site traffic. A follow-up brand lift study showed the campaign was doing its job, with a 20-point lift in awareness and a doubling of purchases.",
    synonyms: [],
  },
  {
    id: 23,
    client: 'SEGA Football Manager 24',
    year: 2025,
    market: 'Global',
    title: 'Global Game Launch',
    industry: ['gaming', 'entertainment'],
    challenges: ['launching in new market', 'global launch', 'improving efficiency'],
    channels: ['paid social', 'programmatic', 'paid search', 'audio'],
    regions: ['americas', 'emea', 'apac'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'audience strategy', 'test & learn'],
    tags: ['multi-market', 'segmentation', 'launch'],
    result: '+102% players vs FM23, -21% cost per download, -28% CPM, -26% CPC',
    summary: 'Built a six-phase global launch strategy across multiple channels, audiences, and markets to scale player growth efficiently.',
    relevanceHook: 'Excellent proof for complex, global, phased launches.',
    competitors: ['EA FC', 'NFL Rivals', 'Top Eleven'],
    story: "Launching Football Manager 24 globally required hitting multiple audiences across different regions simultaneously. We designed a six-phase campaign spanning everything from pre-launch teasers to holiday promos, slicing the audience into core, mid-core, and new players. By adjusting the media mix and messaging for each segment and market, we doubled the player count while cutting the cost per download by 21%.",
    synonyms: [],
  },
  {
    id: 24,
    client: 'Skillz',
    year: 2023,
    market: 'US',
    title: 'Snapchat User Acquisition',
    industry: ['gaming', 'mobile', 'finance'],
    challenges: ['user acquisition', 'improving efficiency', 'fixing measurement'],
    channels: ['paid social', 'snapchat'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'measurement & attribution', 'channel expertise'],
    tags: ['SKAN', 'Kochava', 'iOS'],
    result: '-45% cost per install, 27.4M+ impressions',
    summary: 'Adapted Snapchat strategy to post-ATT measurement constraints and optimized toward stronger downstream signals.',
    relevanceHook: 'Great proof for iOS-era measurement-aware user acquisition.',
    competitors: ['Zynga', 'Scopely', 'Papaya Gaming'],
    synonyms: ['Paid Social UA', 'Facebook Ads', 'Instagram Ads'],
    story: "Skillz had to keep Snapchat working after ATT made mobile measurement much harder. We upgraded the tracking setup, shifted optimization toward a deeper value signal, and found that single-video ads were consistently outperforming other formats. That combination helped bring CPI down by 45% while preserving scale.",
  },
  {
    id: 25,
    client: 'Local Now',
    year: 2023,
    market: 'US',
    title: 'Streaming TV Growth',
    industry: ['streaming', 'media', 'avod', 'news'],
    challenges: ['scaling reach', 'retention', 'user acquisition'],
    channels: ['ctv', 'ott', 'programmatic'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'cost efficiency', 'channel expertise'],
    tags: ['Roku', 'Amazon Fire TV', 'full funnel'],
    result: '+574% revenue, -24% CPI, -41% cost per hour spent in-app',
    summary: 'Built a full-funnel CTV growth strategy across Roku and Fire TV to drive awareness, installs, retention, and revenue.',
    relevanceHook: 'Best fit for AVOD, streaming, and CTV growth stories.',
    competitors: ['Pluto TV', 'Tubi', 'Peacock Free', 'NewsBreak', 'Dave', 'Dave.com', 'Chime', 'Current'],
    synonyms: ['connected tv', 'streaming tv', 'ctv', 'ott', 'dave', 'dave.com', 'Consumer Fintech', 'Neobank'],
    story: 'Local Now wanted more efficient growth across the full funnel, not just cheap installs. We built a CTV-led strategy across Roku and Fire TV to drive awareness, acquisition, and stronger downstream usage, then optimized around real value signals. The result was a huge jump in revenue while also cutting acquisition and engagement costs.',
  },
  {
    id: 26,
    client: 'ASICS',
    year: 2023,
    market: 'Singapore',
    title: 'Website Conversion Optimization',
    industry: ['fashion', 'retail', 'dtc', 'sportswear', 'e-commerce'],
    challenges: ['driving revenue', 'conversion improvement', 'improving efficiency'],
    channels: ['programmatic', 'paid social', 'paid search'],
    regions: ['apac'],
    outcomeTypes: ['scale & growth', 'audience strategy', 'cost efficiency'],
    tags: ['criteo', 'retargeting', 'performance max'],
    result: '+31% visitors YoY, +7% revenue YoY, +11% AOV YoY',
    summary: 'Built a retargeting-first e-commerce growth strategy across Criteo, Meta, and Google to improve direct sales efficiency.',
    relevanceHook: 'Strong fit for DTC retail and conversion-focused growth.',
    competitors: ['Nike', 'Adidas', 'New Balance', 'On Running'],
    synonyms: ['Facebook Ads', 'Instagram Ads', 'paid social'],
    story: "ASICS wanted to drive more direct-to-consumer sales in Singapore while maximizing the efficiency of their media spend. We built a retargeting-first e-commerce strategy, using Criteo to capture high-intent shoppers, layered with Meta and Google Performance Max to drive broader conversion. By focusing tightly on audiences most likely to purchase, we lifted site visitors by 31% YoY while simultaneously growing total revenue and pushing Average Order Value (AOV) up 11%.",
  },
  {
    id: 27,
    client: 'Beam Suntory (Auchentoshan)',
    year: 2022,
    market: 'Singapore, Malaysia, Cambodia, Vietnam',
    title: 'Brand Awareness Campaign',
    industry: ['cpg', 'beverage', 'alcohol'],
    challenges: ['brand repositioning', 'launching in new market', 'scaling awareness'],
    channels: ['youtube', 'ctv', 'programmatic'],
    regions: ['apac'],
    outcomeTypes: ['scale & growth', 'creative effectiveness'],
    tags: ['dco', 'multi-market', 'video'],
    result: '+165% sales volume, +7.5x CTR',
    summary: 'Built a multi-market dynamic creative campaign to reposition whisky for younger audiences across APAC.',
    relevanceHook: 'High-quality proof for brand repositioning and multi-market creative scale.',
    competitors: ['Johnnie Walker', 'Glenfiddich', 'Macallan'],
    synonyms: [],
  },
]

export const filterGroups = {
  industry: ['fitness', 'education', 'health & wellness', 'finance', 'gaming', 'retail', 'fashion', 'streaming', 'saas', 'entertainment', 'cpg', 'media', 'subscription', 'e-commerce'],
  challenge: ['launching in new market', 'improving efficiency', 'scaling reach', 'user acquisition', 'retention', 'brand repositioning', 'creative performance', 'fixing measurement', 'driving revenue', 'brand awareness', 'growing organic acquisition'],
  channel: ['paid search', 'paid social', 'aso', 'programmatic', 'influencers', 'youtube', 'audio', 'ctv', 'tiktok', 'snapchat', 'podcast', 'display', 'native', 'reddit'],
  region: ['americas', 'apac', 'emea'],
  outcomeType: ['cost efficiency', 'scale & growth', 'creative effectiveness', 'measurement & attribution', 'channel expertise', 'audience strategy', 'test & learn', 'fraud & brand safety'],
}
