export const caseStudies = [
  {
    id: 1,
    client: 'Rakuten',
    year: 2023,
    market: 'US',
    title: 'TikTok Creative Optimization',
    industry: ['retail', 'e-commerce'],
    challenges: ['creative performance', 'user acquisition'],
    channels: ['tiktok'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'creative effectiveness', 'test & learn'],
    tags: ['shopping rewards', 'spark ads', 'app installs'],
    result: '-35% CPI, -31% CPA, +77% SKAN click conversion rate',
    summary: 'Used TikTok Creative Exchange and Automatic Creative Optimization to test 40+ permutations and find the best-performing creative mix.',
    relevanceHook: 'Strong proof for TikTok acquisition and performance creative testing.',
    competitors: ['Honey', 'Ibotta', 'Fetch Rewards', 'Capital One Shopping'],
    synonyms: [],
    story: "Rakuten wanted TikTok to work like a serious acquisition channel, not just a place to post brand creative. We brought in TikTok Creative Exchange partners and fed more than 40 creative combinations through Automatic Creative Optimization. That testing discipline helped us find the mix that actually converted, cutting CPA by 34% while lifting installs and purchase rates.",
  },
  {
    id: 2,
    client: 'SoundCloud',
    year: 2022,
    market: 'US',
    title: 'YouTube Acquisition Optimization',
    industry: ['streaming', 'audio'],
    challenges: ['fixing measurement', 'user acquisition'],
    channels: ['youtube'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'measurement & attribution'],
    tags: ['retargeting', 'lookalikes', 'artist acquisition'],
    result: '-82% acquisition costs, -45% CPV, 9% under CPA goal',
    summary: 'Fixed broken measurement, rebuilt audience strategy, and improved creative mix to turn YouTube into the most efficient acquisition channel.',
    relevanceHook: 'Excellent proof for measurement cleanup and turning around an underperforming channel.',
    competitors: ['Spotify', 'Apple Music', 'Tidal', 'Pandora'],
    synonyms: [],
    story: "SoundCloud had a YouTube acquisition problem: the channel was spending, but it was underdelivering. We found gaps in tracking, rebuilt their retargeting structure, and refreshed the creative so the system had better inputs. That reset turned YouTube into their most efficient acquisition channel and brought CPA in 9% under target.",
  },
  {
    id: 3,
    client: 'SoundCloud',
    year: 2022,
    market: 'US',
    title: 'TikTok Influencer User Acquisition',
    industry: ['streaming', 'audio'],
    challenges: ['creative performance', 'user acquisition'],
    channels: ['tiktok', 'influencers'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency'],
    tags: ['spark ads', 'creator content', 'app installs'],
    result: 'Lowest CPA in SoundCloud TikTok history',
    summary: 'Used artist-led creator content and Spark Ads to build authentic TikTok-native acquisition that outperformed prior benchmarks.',
    relevanceHook: 'Great for creator-led social, TikTok-native thinking, and efficient subscription growth.',
    competitors: ['Spotify', 'Apple Music', 'Tidal', 'Pandora'],
    synonyms: [],
    story: "SoundCloud needed TikTok acquisition to feel native, not like recycled ad creative. We worked with artists and creator-led content, then amplified the strongest assets through Spark Ads. Because the work felt native to the platform, it drove the lowest CPA SoundCloud had seen on TikTok.",
  },
  {
    id: 4,
    client: 'Local Now',
    year: 2021,
    market: 'US',
    title: 'App Store Optimization',
    industry: ['streaming', 'media'],
    challenges: ['growing organic acquisition'],
    channels: ['aso'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'channel expertise'],
    tags: ['Google Play', 'organic', 'keywords'],
    result: '+80% Top 10 keywords, +4% conversion lift, +35% organic downloads',
    summary: 'Overhauled Google Play keyword strategy, title, and short description to improve discoverability and conversion.',
    relevanceHook: 'Clean proof for ASO and organic app growth.',
    competitors: [],
    synonyms: [],
    story: 'Local Now needed to improve how efficiently it captured organic app demand. We overhauled the Google Play listing strategy—keywords, title, and description—to better match what users were actually searching for. That drove stronger keyword rankings and a meaningful lift in organic downloads.',
  },
  {
    id: 5,
    client: 'FanDuel',
    year: 2020,
    market: 'US',
    title: 'Reddit Creative Testing',
    industry: ['gaming'],
    challenges: ['creative performance'],
    channels: ['reddit'],
    regions: ['americas'],
    outcomeTypes: ['creative effectiveness', 'test & learn'],
    tags: ['meme creative', 'regulated gaming'],
    result: '+17% higher conversion vs control',
    summary: 'Created Reddit-native meme-based ad variants that outperformed standard branded creative across the channel.',
    relevanceHook: 'Best for channel-native creative thinking and social platform adaptation.',
    competitors: ['DraftKings', 'BetMGM', 'Caesars Sportsbook'],
    synonyms: [],
    story: "FanDuel wanted to crack Reddit, but standard display ads weren't converting. We built meme-inspired creative variants specifically designed for how Redditors communicate. By speaking the platform's language instead of forcing a standard brand ad, the native concepts outperformed the control group by 17%.",
  },
  {
    id: 6,
    client: 'Pokémon GO',
    year: 2020,
    market: 'US',
    title: 'Full Funnel Campaign',
    industry: ['gaming'],
    challenges: ['full-funnel growth', 'user acquisition'],
    channels: ['ctv', 'paid social', 'programmatic'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth'],
    tags: ['full funnel', 'launch'],
    result: 'Significant DAU and new user uplift',
    summary: 'Built a full-funnel launch campaign using CTV, DOOH, paid social, and retargeting to drive awareness and new user growth.',
    relevanceHook: 'Strong example for multi-channel launch orchestration.',
    competitors: [],
    synonyms: [],
    story: "When Pokémon GO needed a massive acquisition push, we orchestrated a true full-funnel approach. We used CTV and digital out-of-home in specific markets to build awareness, then captured that intent with targeted social and programmatic ads. That coordinated layering drove significant lifts in both new users and daily active players.",
  },
  {
    id: 7,
    client: 'Neou Fitness',
    year: 2020,
    market: 'US / CA / UK / AU',
    title: 'Creative Effectiveness & User Acquisition',
    industry: ['fitness', 'health & wellness'],
    challenges: ['creative performance', 'user acquisition'],
    channels: ['paid social'],
    regions: ['americas', 'emea'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'creative effectiveness', 'test & learn'],
    tags: ['international expansion', 'a/b testing'],
    result: '+48% subscriptions, -122% cost per subscription',
    summary: 'A/B tested static and video creative, then scaled winning concepts internationally across multiple markets.',
    relevanceHook: 'Great proof for fitness subscription growth and creative iteration at scale.',
    competitors: ['Peloton', 'Nike Training Club', 'Daily Burn'],
    synonyms: [],
    story: "Neou Fitness needed to scale subscriptions fast. We started by aggressively A/B testing static and video creative on paid social to find out exactly what resonated. Once we had a winning template, we scaled those proven concepts internationally across the US, Canada, the UK, and Australia, dropping their cost per subscription by over 120% in five months.",
  },
  {
    id: 8,
    client: 'Amazon Shopping',
    year: 2020,
    market: 'US',
    title: 'Ad Fraud Protection',
    industry: ['retail', 'e-commerce'],
    challenges: ['fraud reduction', 'measurement cleanup'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['fraud & brand safety', 'measurement & attribution'],
    tags: ['ad fraud', 'programmatic'],
    result: '+176% monthly install volume, $1.4M fraud savings, -31% fraud rate',
    summary: 'Implemented fraud monitoring and source blacklisting across programmatic placements to protect spend and improve quality.',
    relevanceHook: 'Best example for fraud reduction, media quality control, and performance protection.',
    competitors: [],
    synonyms: [],
    story: "Amazon Shopping was spending heavily on programmatic, but we needed to ensure that budget was driving real installs, not just funding ad fraud. We partnered with a third-party monitor, built strict prevention rules, and proactively blacklisted high-fraud sources on a weekly basis. That active defense cut their fraud rate by 31% and saved them $1.4 million.",
  },
  {
    id: 9,
    client: 'Amazon Shopping',
    year: 2020,
    market: 'US',
    title: 'Creative Testing & Programmatic',
    industry: ['retail', 'e-commerce'],
    challenges: [],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: [],
    tags: ['cta testing', 'creative testing'],
    result: '+176% iOS CTR, +54% Android conversion rate, +27% iOS conversion rate',
    summary: 'Ran sequential CTA and creative-theme tests across programmatic display to identify the strongest-performing combinations.',
    relevanceHook: 'Proof for disciplined creative testing and incrementality in lower-funnel media.',
    competitors: [],
    synonyms: [],
    story: "Amazon Shopping needed to know whether programmatic was truly driving new growth or just taking credit for users who would have converted anyway. We set up an exposed-versus-control test through DSPs and measured the lift over a 30-day window. The result gave them hard proof that the channel was incremental and worth scaling.",
  },
  {
    id: 10,
    client: 'Amazon Shopping',
    year: 2020,
    market: 'US',
    title: 'Incrementality Testing',
    industry: ['retail', 'e-commerce'],
    challenges: ['fixing measurement', 'incrementality'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['measurement & attribution', 'test & learn'],
    tags: ['DSP', 'incrementality', 'exposed vs control'],
    result: '+130% Android conversion rate, >80% overall lift',
    summary: 'Built exposed vs control experiments to validate incremental value from programmatic media with statistical rigor.',
    relevanceHook: 'Best proof point for measurement maturity and incrementality validation.',
    competitors: [],
    synonyms: [],
    story: "Amazon Shopping needed to know whether programmatic was truly driving new growth or just taking credit for users who would have converted anyway. We set up an exposed-versus-control test through DSPs and measured the lift over a 30-day window. The result gave them hard proof that the channel was incremental and worth scaling.",
  },
  {
    id: 11,
    client: 'Audible',
    year: 2020,
    market: 'Canada',
    title: 'Audience Engagement via Custom Content',
    industry: ['audio', 'publishing'],
    challenges: ['brand awareness', 'audience engagement'],
    channels: ['display'],
    regions: ['americas'],
    outcomeTypes: ['audience strategy'],
    tags: ['custom content', 'high-impact display', 'brand'],
    result: '18x higher content engagement, 2x higher CTR',
    summary: 'Used editorial content and high-impact placements to drive stronger engagement and consideration for Audible.',
    relevanceHook: 'Useful for upper-funnel brand work with editorial storytelling.',
    competitors: [],
    synonyms: [],
    story: "Audible wanted to capture upper-funnel attention during the pandemic by giving people a reason to engage, not just an ad to click. We partnered with premium publishers to create co-branded listicles and quizzes, and paired them with high-impact spotlight ads. That editorial approach drove 18 times more engagement than standard banners.",
  },
  {
    id: 12,
    client: 'Audible',
    year: 2020,
    market: 'Canada',
    title: 'Incrementality Testing via Google App Campaigns',
    industry: ['audio', 'publishing'],
    challenges: ['fixing measurement', 'incrementality'],
    channels: ['paid search'],
    regions: ['americas'],
    outcomeTypes: ['measurement & attribution', 'cost efficiency', 'test & learn'],
    tags: ['geo split', 'incrementality', 'geo holdout'],
    result: '+17% incremental uplift in trials, +15% improved cost per trial',
    summary: 'Used randomized geo holdouts to measure true incremental trial lift from Google App Campaigns.',
    relevanceHook: 'Strong proof for rigorous channel validation and cost discipline.',
    competitors: [],
    synonyms: [],
    story: "Audible wanted a cleaner answer on whether Google App Campaigns were really moving the business. Rather than rely on platform reporting, we built a geo-holdout test across Canadian markets to isolate true incremental impact. That gave them a more credible read on performance and showed a 17% lift in trial starts.",
  },
  {
    id: 13,
    client: 'Boston Globe',
    year: 2020,
    market: 'US',
    title: 'Creative & Landing Page Testing',
    industry: ['media', 'publishing'],
    challenges: ['creative performance', 'conversion improvement'],
    channels: ['paid social', 'native'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'test & learn'],
    tags: ['landing page testing', 'subscription acquisition'],
    result: '45% improvement in cost per subscription',
    summary: 'Matched channel-specific creative and landing page strategies to reduce cost per subscription across paid social and native.',
    relevanceHook: 'Best for subscription conversion and landing page optimization proof.',
    competitors: [],
    synonyms: [],
    story: "The Boston Globe needed to acquire digital subscribers more efficiently. We realized that users from native ads wanted content, while users from paid social were looking for a deal. By matching the landing page experience—content-led versus offer-led—to the traffic source, we removed friction and dropped the cost per subscription by 45%.",
  },
  {
    id: 14,
    client: 'ComiXology',
    year: 2020,
    market: 'US',
    title: 'Landing Page Testing',
    industry: ['entertainment', 'e-commerce'],
    challenges: ['conversion improvement', 'driving revenue'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'test & learn'],
    tags: ['landing page', 'a/b testing'],
    result: '-22% cost per purchase, +74% purchases, +42% revenue',
    summary: 'A/B tested alternative landing page sale formats to reduce friction and increase purchase volume.',
    relevanceHook: 'Strong example for e-commerce post-click optimization.',
    competitors: [],
    synonyms: [],
    story: "For ComiXology, we knew getting a click wasn't enough if the landing page didn't convert. We A/B tested a focused 6-comic preview against a sprawling 30-comic layout. It turned out the cleaner, shorter page reduced decision fatigue and drove significantly higher purchase rates, boosting revenue by 42% while lowering costs.",
  },
  {
    id: 15,
    client: 'Pinna',
    year: 2020,
    market: 'US',
    title: 'Native vs. Display User Acquisition',
    industry: ['audio', 'family'],
    challenges: ['user acquisition'],
    channels: ['native', 'display'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'test & learn', 'channel expertise'],
    tags: ['channel comparison', 'native', 'display'],
    result: 'Native: 8x more efficient CPT. Display: 41% higher CTR',
    summary: 'Compared native and dynamic display by funnel stage to understand the right job for each channel.',
    relevanceHook: 'Useful proof for channel-role clarity and family subscription growth.',
    competitors: [],
    synonyms: [],
    story: "Pinna needed to figure out how to best use native and display ads for their family audio app. By running them side by side, we proved they did completely different jobs: display was great for cheap, upper-funnel reach and consideration, while native drove actual trial conversions eight times more efficiently. That clarity let us optimize the budget for the whole funnel.",
  },
  {
    id: 16,
    client: 'Groupon',
    year: 2026,
    market: 'US, EMEA',
    title: 'AI-Powered Brand Creative',
    industry: ['retail', 'e-commerce'],
    challenges: ['brand awareness', 'creative performance'],
    channels: [],
    regions: ['americas', 'emea'],
    outcomeTypes: ['creative effectiveness'],
    tags: ['ai creative', 'localization', 'brand reactivation', 'brand lift'],
    result: '+11% Search Lift, +22% Brand Salience, +31% Unaided Ad Recall',
    summary: 'Built a human-directed, AI-enabled production model to create multi-market brand creative faster and more efficiently.',
    relevanceHook: 'High-impact proof for modern creative production and brand lift.',
    competitors: [],
    synonyms: [],
    story: "Groupon needed to move faster across multiple cities without getting trapped in a slow, expensive production cycle. We used AI as a speed layer for storyboard development and localization, while keeping strong human direction over the final work. That let the team bring campaign-ready creative to market far faster and drove a 31% lift in unaided ad recall.",
  },
  {
    id: 17,
    client: 'Canva',
    year: 2026,
    market: 'India',
    title: 'Incremental Reach via OTT & Audio',
    industry: ['saas'],
    challenges: ['scaling reach', 'brand awareness'],
    channels: ['ott', 'audio'],
    regions: ['apac'],
    outcomeTypes: ['scale & growth', 'audience strategy'],
    tags: ['india', 'incremental reach', 'reach planning'],
    result: '300M+ impressions, 80M unique viewers, 60% incremental reach in Month 2',
    summary: 'Layered OTT and audio strategically to create broad but efficient brand reach across India with low audience overlap.',
    relevanceHook: 'Excellent proof for emerging-market reach and cross-channel brand planning.',
    competitors: [],
    synonyms: [],
    story: 'Canva wanted to scale brand reach in India without wasting spend on overlapping audiences. We combined OTT and audio in a complementary way so each channel expanded reach instead of duplicating it. That gave them massive scale and strong incremental reach very quickly.',
  },
  {
    id: 18,
    client: 'Headspace',
    year: 2025,
    market: 'US',
    title: 'Custom Store Listings for Sleep',
    industry: ['health & wellness', 'fitness'],
    challenges: ['growing organic acquisition', 'conversion improvement'],
    channels: ['aso'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'channel expertise'],
    tags: ['Sleep Week', 'Google Play', 'custom store listing'],
    result: '+31% sleep-related visitors, +49% acquisitions, +26% CVR',
    summary: 'Created a sleep-themed Custom Store Listing to win higher-intent wellness traffic and improve store conversion.',
    relevanceHook: 'Clean proof for ASO, category-specific acquisition, and health app growth.',
    competitors: [],
    synonyms: [],
    story: "Headspace wanted to capture people already searching for sleep support, not just drive generic store traffic. We built a sleep-focused Custom Store Listing around Sleep Week, aligning keywords, screenshots, and visual cues to that specific use case. That tighter message-to-store fit lifted acquisitions by 49% and improved conversion rate by 26%.",
  },
  {
    id: 19,
    client: 'Maya Bank',
    year: 2025,
    market: 'Philippines',
    title: 'ASO Custom Store Listings',
    industry: ['finance'],
    challenges: ['conversion improvement', 'growing organic acquisition'],
    channels: ['aso'],
    regions: ['apac'],
    outcomeTypes: ['scale & growth', 'channel expertise'],
    tags: ['lending', 'Google Play', 'custom store listing'],
    result: '+31% new-user CVR, +22% reinstall CVR, +106% top keyword CVR',
    summary: 'Built lending-specific Custom Store Listings to improve high-intent conversion for a digital banking product.',
    relevanceHook: 'Best fit for fintech, lending, and ASO-led conversion improvement.',
    competitors: [],
    synonyms: [],
    story: 'Maya Bank needed to improve conversion for high-intent lending users in the Philippines. We built lending-specific Custom Store Listings so people searching for exactly those solutions saw a much more relevant store experience. That sharper alignment lifted new-user conversion by 31% and more than doubled top-keyword conversion.',
  },
  {
    id: 20,
    client: 'Rodd & Gunn',
    year: 2025,
    market: 'North America',
    title: 'Loyalty Day Flash Sale',
    industry: ['fashion', 'retail', 'e-commerce'],
    challenges: ['retention', 'driving revenue'],
    channels: ['paid social', 'paid search'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'audience strategy'],
    tags: ['flash sale', 'loyalty', 'meta'],
    result: '+500% purchases, +556% revenue, +56.6% ROAS',
    summary: 'Used a two-phase Meta and SEM program to grow loyalty membership, then monetize it through a highly targeted flash sale.',
    relevanceHook: 'Very strong proof for DTC retention and monetization.',
    competitors: [],
    synonyms: [],
    story: "Rodd & Gunn wanted loyalty to behave like a revenue engine, not just a retention program. We first used Meta lead ads to build the member base, then followed with a tightly timed 30-hour flash sale aimed squarely at conversion. The two-phase structure helped turn audience growth into immediate commercial return, driving a 500% jump in purchases.",
  },
  {
    id: 21,
    client: 'TickPick',
    year: 2024,
    market: 'US',
    title: 'Full-Funnel Programmatic',
    industry: ['entertainment', 'ticketing'],
    challenges: ['full-funnel growth', 'improving efficiency'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'audience strategy'],
    tags: ['DSP', 'prospecting', 'retargeting'],
    result: '+65% improved CPA, 22M+ unique users reached',
    summary: 'Built a three-month programmatic strategy balancing prospecting and retargeting to move users through the ticket-buying journey.',
    relevanceHook: 'Great for marketplace growth and lower-funnel programmatic proof.',
    competitors: [],
    synonyms: [],
    story: "TickPick needed to grow ticket sales without losing efficiency. We split the programmatic plan into two clear jobs: prospecting to bring the right people into the funnel, and retargeting to convert them with sharper no-fee messaging. That structure let us scale reach materially while improving CPA by 65%.",
  },
  {
    id: 22,
    client: 'TickPick',
    year: 2024,
    market: 'US',
    title: 'Podcast Brand Awareness',
    industry: ['entertainment', 'ticketing'],
    challenges: ['brand awareness', 'measurement'],
    channels: ['podcast', 'audio'],
    regions: ['americas'],
    outcomeTypes: ['measurement & attribution', 'scale & growth'],
    tags: ['host-read', 'brand lift', 'podcast'],
    result: '+20PPT brand awareness, +117% purchases, +144% ROAS',
    summary: 'Ran host-read podcast campaigns across sports and entertainment shows and validated performance with a brand lift study.',
    relevanceHook: 'Strong proof for audio and brand lift with real commercial outcomes.',
    competitors: [],
    synonyms: [],
    story: "TickPick wanted to use audio to challenge much larger ticketing competitors. We built the plan around host-read placements in sports and entertainment podcasts, then optimized the mix based on which shows were actually driving site traffic. A follow-up brand lift study showed the campaign was doing its job, with a 20-point lift in awareness and a doubling of purchases.",
  },
  {
    id: 23,
    client: 'SEGA Football Manager 24',
    year: 2025,
    market: 'Global',
    title: 'Global Game Launch',
    industry: ['gaming'],
    challenges: ['global launch', 'user acquisition'],
    channels: ['paid social', 'programmatic', 'paid search'],
    regions: ['americas', 'emea', 'apac'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'audience strategy'],
    tags: ['multi-market', 'segmentation', 'launch', 'global'],
    result: '+102% players vs FM23, -21% cost per download, -28% CPM, -26% CPC',
    summary: 'Built a six-phase global launch strategy across multiple channels, audiences, and markets to scale player growth efficiently.',
    relevanceHook: 'Excellent proof for complex, global, phased launches.',
    competitors: [],
    synonyms: [],
    story: "Launching Football Manager 24 globally required hitting multiple audiences across different regions simultaneously. We designed a six-phase campaign spanning everything from pre-launch teasers to holiday promos, slicing the audience into core, mid-core, and new players. By adjusting the media mix and messaging for each segment and market, we doubled the player count while cutting the cost per download by 21%.",
  },
  {
    id: 24,
    client: 'Skillz',
    year: 2023,
    market: 'US',
    title: 'Snapchat User Acquisition',
    industry: ['gaming'],
    challenges: ['user acquisition', 'fixing measurement'],
    channels: ['snapchat'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'measurement & attribution', 'channel expertise'],
    tags: ['SKAN', 'iOS', 'post-ATT', 'mobile measurement'],
    result: '-45% cost per install, 27.4M+ impressions',
    summary: 'Adapted Snapchat strategy to post-ATT measurement constraints and optimized toward stronger downstream signals.',
    relevanceHook: 'Great proof for iOS-era measurement-aware user acquisition.',
    competitors: [],
    synonyms: [],
    story: "Skillz had to keep Snapchat working after ATT made mobile measurement much harder. We upgraded the tracking setup, shifted optimization toward a deeper value signal, and found that single-video ads were consistently outperforming other formats. That combination helped bring CPI down by 45% while preserving scale.",
  },
  {
    id: 25,
    client: 'Local Now',
    year: 2023,
    market: 'US',
    title: 'Streaming TV Growth',
    industry: ['streaming', 'media'],
    challenges: ['user acquisition', 'retention'],
    channels: ['ctv', 'ott'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'cost efficiency', 'channel expertise'],
    tags: ['Roku', 'Amazon Fire TV', 'full funnel', 'CTV'],
    result: '+574% revenue, -24% CPI, -41% cost per hour spent in-app',
    summary: 'Built a full-funnel CTV growth strategy across Roku and Fire TV to drive awareness, installs, retention, and revenue.',
    relevanceHook: 'Best fit for AVOD, streaming, and CTV growth stories.',
    competitors: [],
    synonyms: [],
    story: 'Local Now wanted more efficient growth across the full funnel, not just cheap installs. We built a CTV-led strategy across Roku and Fire TV to drive awareness, acquisition, and stronger downstream usage, then optimized around real value signals. The result was a huge jump in revenue while also cutting acquisition and engagement costs.',
  },
  {
    id: 26,
    client: 'ASICS',
    year: 2023,
    market: 'Singapore',
    title: 'Website Conversion Optimization',
    industry: ['fashion', 'retail', 'e-commerce'],
    challenges: ['driving revenue', 'conversion improvement', 'improving efficiency'],
    channels: ['programmatic', 'paid social', 'paid search'],
    regions: ['apac'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'audience strategy'],
    tags: ['criteo', 'retargeting', 'performance max', 'meta'],
    result: '+31% visitors YoY, +7% revenue YoY, +11% AOV YoY',
    summary: 'Built a retargeting-first e-commerce growth strategy across Criteo, Meta, and Google to improve direct sales efficiency.',
    relevanceHook: 'Strong fit for DTC retail and conversion-focused growth.',
    competitors: [],
    synonyms: [],
    story: "ASICS wanted to drive more direct-to-consumer sales in Singapore while maximizing the efficiency of their media spend. We built a retargeting-first e-commerce strategy, using Criteo to capture high-intent shoppers, layered with Meta and Google Performance Max to drive broader conversion. By focusing tightly on audiences most likely to purchase, we lifted site visitors by 31% YoY while simultaneously growing total revenue and pushing Average Order Value (AOV) up 11%.",
  },
  {
    id: 27,
    client: 'Beam Suntory (Auchentoshan)',
    year: 2022,
    market: 'Singapore, Malaysia, Cambodia, Vietnam',
    title: 'Brand Awareness Campaign',
    industry: ['cpg'],
    challenges: ['brand repositioning', 'brand awareness'],
    channels: [],
    regions: ['apac'],
    outcomeTypes: ['creative effectiveness'],
    tags: ['dco', 'multi-market', 'video', 'brand repositioning'],
    result: '+165% sales volume, +7.5x CTR',
    summary: 'Built a multi-market dynamic creative campaign to reposition whisky for younger audiences across APAC.',
    relevanceHook: 'High-quality proof for brand repositioning and multi-market creative scale.',
    competitors: [],
    synonyms: [],
    story: '',
  },

  {
    id: 28,
    client: 'Audible',
    year: 2022,
    market: 'US',
    title: 'TikTok Influencer Campaign',
    industry: ['audio', 'publishing'],
    challenges: ['brand awareness', 'user acquisition'],
    channels: ['tiktok', 'influencers'],
    regions: ['americas'],
    outcomeTypes: [],
    tags: ['micro-influencers', 'creator content', 'subscriptions'],
    result: '55k organic video views, $0.31 cost per view, 8% average engagement rate',
    summary: 'Partnered with TikTok micro-influencers and creators to grow Audible visibility and subscription interest with relatable, entertainment-led content.',
    relevanceHook: 'Useful proof for creator-led TikTok campaigns in subscription audio.',
    competitors: [],
    synonyms: [],
    story: "Audible needed a stronger way to gain new subscribers in a crowded market. We partnered with micro-influencers and creators on TikTok, using relatable entertainment-led content that showed how Audible fits into daily life. The campaign lifted visibility efficiently, generating 55k organic views with an 8% engagement rate.",
  },
  {
    id: 29,
    client: 'The Weather Channel',
    year: 2022,
    market: 'US',
    title: 'Streaming Product Launch Testing',
    industry: ['streaming', 'media'],
    challenges: ['user acquisition'],
    channels: ['display', 'ctv', 'ott'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'test & learn'],
    tags: ['amazon fire tv', 'roku', 'weather triggers', 'trial acquisition'],
    result: '-64% cost per trial, -79% cost per subscription, +44% install rate',
    summary: 'Tested geography, messaging, and weather-triggered media activation to build the 2023 acquisition strategy for The Weather Channel streaming product.',
    relevanceHook: 'Strong example of explicit testing and real-time trigger-led media activation.',
    competitors: [],
    synonyms: [],
    story: "The Weather Channel needed to launch its direct-to-consumer streaming product and learn fast. We tested geography, offers, and creative while structuring the media plan to switch on around key weather events across Amazon Fire TV and Roku. That testing program built the playbook for 2023 and sharply reduced both trial and subscription costs.",
  },
  {
    id: 30,
    client: 'Local Now',
    year: 2023,
    market: 'US',
    title: 'Optimizing CTV Features',
    industry: ['streaming', 'media'],
    challenges: ['user acquisition', 'retention'],
    channels: ['ctv', 'ott'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'scale & growth', 'test & learn'],
    tags: ['amazon fire tv', 'roku', 'featured row', 'tile optimization'],
    result: '-21% CPI YoY, +69% downloads, +50% new users YoY on Roku',
    summary: 'Tested platform-native CTV features across Amazon Fire TV and Roku to improve acquisition efficiency and downstream engagement.',
    relevanceHook: 'Good fit for CTV feature testing and AVOD growth.',
    competitors: [],
    synonyms: [],
    story: "Local Now needed to keep CTV growth efficient while sustaining audience quality. We tested newer platform-native units like automated tile selection, news-aligned placements, and Roku featured row takeovers to improve both acquisition and engagement. Those tests helped lower CPI while driving materially more downloads and new users.",
  },
  {
    id: 31,
    client: 'Local Now',
    year: 2022,
    market: 'US',
    title: 'Programmatic CTV Efficiency',
    industry: ['streaming', 'media'],
    challenges: ['brand awareness', 'user acquisition'],
    channels: ['programmatic', 'ctv'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'audience strategy'],
    tags: ['trade desk', 'roku oneview', 'private marketplace deals'],
    result: '50% CPI reduction, 17% CPM reduction, 0.11% VCR increase',
    summary: 'Balanced broad Roku OneView scale with more targeted Trade Desk inventory to improve CTV efficiency while holding awareness quality.',
    relevanceHook: 'Useful proof for programmatic CTV planning across scale and efficiency objectives.',
    competitors: [],
    synonyms: [],
    story: "Local Now needed CTV to balance view quality with install efficiency. We split spend across Roku OneView for scale and Trade Desk for more tailored audience and deal-based buying, then optimized the mix over time. That lowered CPI and CPM while slightly improving completed-view performance.",
  },
  {
    id: 32,
    client: 'Local Now',
    year: 2023,
    market: 'US',
    title: 'Meta Audience Expansion',
    industry: ['streaming', 'media'],
    challenges: ['retention', 'user acquisition'],
    channels: ['paid social'],
    regions: ['americas'],
    outcomeTypes: ['audience strategy', 'scale & growth'],
    tags: ['meta', 'interest targeting', 'content segments'],
    result: '+210% increase in new sessions, +300% 5+ minute sessions, +168% total page views',
    summary: 'Shifted Meta targeting from demographic audiences to content-interest segments to improve traffic quality and reduce fatigue.',
    relevanceHook: 'Strong proof for audience strategy and interest-based social targeting.',
    competitors: [],
    synonyms: [],
    story: "Local Now needed paid social to keep bringing new high-quality visitors without burning out the same audiences. We shifted Meta targeting from broad demographic assumptions to interest-led segments around local news, movies, and real crime content. That change improved session quality and volume materially.",
  },
  {
    id: 33,
    client: 'SoundCloud',
    year: 2022,
    market: 'US / CA / DE / UK / FR / NL',
    title: 'Apple Search Ads Custom Product Pages',
    industry: ['streaming', 'audio'],
    challenges: ['user acquisition'],
    channels: ['paid search'],
    regions: ['americas', 'emea'],
    outcomeTypes: ['cost efficiency', 'creative effectiveness'],
    tags: ['apple search ads', 'custom product pages', 'competitor keywords'],
    result: '+50% cost per install improvement, +10% tap-through rate, +8% cost per tap improvement',
    summary: 'Used Apple Search Ads Custom Product Pages to match keyword intent with tighter App Store messaging and improve acquisition efficiency.',
    relevanceHook: 'Excellent proof for App Store landing-page style optimization through Apple Search Ads.',
    competitors: ['Spotify', 'Apple Music', 'Tidal', 'Pandora'],
    synonyms: [],
    story: "SoundCloud wanted a stronger way to win users searching in the App Store. We tested Custom Product Pages, including one centered on unlimited skips messaging, and paired them with keyword-driven Apple Search Ads across multiple markets. That tighter message-to-intent match improved CPI, tap-through rate, and cost per tap.",
  },

  {
    id: 34,
    client: 'Gopuff',
    year: 2025,
    market: 'US',
    title: 'Influencer-Led New User Growth',
    industry: ['retail', 'e-commerce'],
    challenges: ['brand awareness', 'user acquisition'],
    channels: ['influencers'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth'],
    tags: ['instant commerce', 'first orders', 'creator content'],
    result: 'Prompted first-time orders through creator-led awareness content',
    summary: 'Used influencer content to explain Gopuff’s everyday relevance and drive first-time orders in a competitive delivery category.',
    relevanceHook: 'Useful proof for creator-led acquisition in instant commerce.',
    competitors: ['Instacart', 'DoorDash', 'Uber Eats'],
    synonyms: [],
    story: "Gopuff needed to grow new users in a market where speed, fees, and convenience are compared constantly. We used influencer content to highlight the service’s everyday relevance across different shopping moments and drive first-time orders more naturally. The work focused on educating consumers on why Gopuff matters, not just pushing a generic delivery ad.",
  },
  {
    id: 35,
    client: 'Five Iron Golf',
    year: 2025,
    market: 'US',
    title: 'Programmatic DOOH Brand Lift',
    industry: ['sports'],
    challenges: ['brand awareness', 'measurement'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['measurement & attribution', 'scale & growth'],
    tags: ['dooh', 'brand lift study', 'multi-city'],
    result: '+40% brand awareness, +20% brand consideration, estimated 11% sales uplift',
    summary: 'Activated a programmatic DOOH campaign across four U.S. cities and validated impact with brand lift and sales analysis.',
    relevanceHook: 'Strong proof that DOOH can be measured beyond impressions.',
    competitors: [],
    synonyms: [],
    story: "Five Iron Golf wanted out-of-home to be measured like a real growth channel instead of a blind awareness bet. We ran a targeted programmatic DOOH campaign across four U.S. cities, used whitelisted venue selection and scheduling controls, then paired it with brand lift and post-campaign sales analysis. That proved the channel was driving both brand movement and commercial impact.",
  },
  {
    id: 36,
    client: 'Tinker DIY',
    year: 2025,
    market: 'US',
    title: 'Full-Funnel New Channel Expansion',
    industry: ['saas'],
    challenges: ['brand awareness', 'user acquisition', 'driving revenue'],
    channels: ['paid search', 'paid social', 'tiktok', 'programmatic', 'reddit', 'ctv', 'audio'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'creative effectiveness'],
    tags: ['ugc', 'women diyers', 'automotive vertical', 'brand lift'],
    result: '162k registrations, +50% app installs, +21% unaided brand recall',
    summary: 'Built a full-funnel expansion plan across core and new channels using UGC, vertical messaging, and brand-building media.',
    relevanceHook: 'Strong proof for expanding beyond core performance channels without losing conversion focus.',
    competitors: [],
    synonyms: [],
    story: "Tinker DIY needed more than incremental gains from its existing channels. We built a fuller funnel plan that combined search, Meta, TikTok, and Apple Search Ads with new channels like CTV, programmatic audio, DOOH, Reddit, and YouTube Shorts. Paired with UGC-led creative and vertical messaging, that mix drove registrations above target and lifted both installs and brand recall.",
  },
  {
    id: 37,
    client: 'Mobile Premier League',
    year: 2025,
    market: 'Brazil',
    title: 'Localized Creative Growth',
    industry: ['gaming'],
    challenges: ['creative performance', 'user acquisition'],
    channels: ['paid social', 'paid search', 'programmatic'],
    regions: ['latam'],
    outcomeTypes: ['creative effectiveness', 'cost efficiency', 'test & learn'],
    tags: ['localization', 'brazil', 'human-led creative', 'a/b testing'],
    result: '-40% CPI, -25% cost per first-time depositor, -22% cost per non-cannibalized DAU',
    summary: 'Rebuilt MPL Brazil creative around human-led, culturally specific storytelling and validated the approach through explicit testing.',
    relevanceHook: 'Excellent proof for localization that goes beyond translation.',
    competitors: [],
    synonyms: ['MPL'],
    story: "MPL needed its Brazil launch creative to feel locally credible, not just translated. We shifted from product-heavy assets to human-led storytelling with Brazilian faces, slang, and culturally specific references, then explicitly tested those against product-only creative. The localized approach materially improved CPI and first-time depositor efficiency as budgets scaled.",
  },
  {
    id: 38,
    client: 'Mobile Premier League',
    year: 2025,
    market: 'Brazil',
    title: 'Localized Programmatic User Acquisition',
    industry: ['gaming'],
    challenges: ['user acquisition'],
    channels: ['programmatic'],
    regions: ['latam'],
    outcomeTypes: ['scale & growth', 'cost efficiency'],
    tags: ['localization', 'programmatic-first', 'apk', 'ios'],
    result: '+260% app installs, +250% first-time deposits, +175% new paying users',
    summary: 'Used a fully localized, programmatic-first acquisition strategy to scale MPL efficiently in Brazil despite platform policy constraints.',
    relevanceHook: 'Strong proof for market entry and programmatic-led scale in a restricted category.',
    competitors: [],
    synonyms: ['MPL'],
    story: "MPL needed to enter Brazil with both scale and cultural credibility while navigating category restrictions on major platforms. We localized the full funnel in Portuguese, introduced locally relevant games like Truco, soft-launched through APK, then expanded into iOS while leaning on programmatic partners for scale. That approach drove major growth in installs, first-time deposits, and paying users while keeping CPI efficient.",
  },
  {
    id: 39,
    client: 'Mobile Premier League',
    year: 2024,
    market: 'US',
    title: 'App Store Optimization',
    industry: ['gaming'],
    challenges: ['growing organic acquisition', 'conversion improvement'],
    channels: ['aso'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'channel expertise', 'test & learn'],
    tags: ['ios', 'keyword optimization', 'product page optimization', 'in-app events'],
    result: '+24% organic installs, +67% ranked keywords, +200% product page views',
    summary: 'Improved MPL’s iOS organic growth through keyword optimization, product page testing, and seasonal in-app event strategy.',
    relevanceHook: 'Strong ASO proof for competitive gaming categories.',
    competitors: [],
    synonyms: ['MPL'],
    story: "MPL wanted more organic growth from the App Store in a crowded real-money gaming category. We ran multiple rounds of keyword optimization, tested product page elements, and used seasonal in-app events and screenshot updates to keep the storefront relevant. That combination improved rankings, product page traffic, and total organic installs.",
  },
  {
    id: 40,
    client: 'Mobile Premier League',
    year: 2024,
    market: 'US',
    title: 'Mission-Based Incentive Channels',
    industry: ['gaming'],
    challenges: ['retention', 'driving revenue'],
    channels: [],
    regions: ['americas'],
    outcomeTypes: ['scale & growth'],
    tags: ['missions', 'incentives', 'gmv'],
    result: '+90% Day 7 ROAS, +95% Day 7 retention, 3.5x GMV per user',
    summary: 'Designed a mission-based incentive system tied to deposits and game thresholds to improve retention, ROAS, and GMV per user.',
    relevanceHook: 'Good proof for incentive design tied to monetization outcomes.',
    competitors: [],
    synonyms: ['MPL'],
    story: "MPL wanted incentive channels to drive stronger revenue without sacrificing long-term retention. We built a tiered mission system, set minimum deposit thresholds, and aligned landing pages and incentive messaging around high-value games. That structure improved short-term ROAS, retention, and GMV per user.",
  },
  {
    id: 41,
    client: 'Mobile Premier League',
    year: 2024,
    market: 'US',
    title: 'ROAS Growth via Card-Game Journey',
    industry: ['gaming'],
    challenges: ['driving revenue', 'retention'],
    channels: ['programmatic'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'audience strategy'],
    tags: ['custom product pages', 'first-game experience', 'card games'],
    result: '+40% Day 7 ROAS, 2x GMV per user, +30% Day 30 ROAS',
    summary: 'Refocused acquisition and onboarding around high-value card games to improve ROAS and user value.',
    relevanceHook: 'Useful proof for aligning acquisition with downstream monetization behavior.',
    competitors: [],
    synonyms: ['MPL'],
    story: "MPL wanted to improve ROAS by improving the user journey, not just bidding harder. We focused acquisition and onboarding around higher-value card games like Gin Rummy, Spades, and 3 Card Flush, then reinforced that journey through creatives, custom product pages, and first-game experience changes. That shift materially improved both ROAS and GMV per user.",
  },

  {
    id: 42,
    client: 'Rakuten',
    year: 2023,
    market: 'US',
    title: 'TikTok Creator Mix Optimization',
    industry: ['retail', 'e-commerce'],
    challenges: ['creative performance', 'user acquisition'],
    channels: ['tiktok', 'influencers'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'creative effectiveness', 'test & learn'],
    tags: ['ugc creators', 'micro-influencers', 'creator testing'],
    result: '-35% CPI, -33% cost per sign-up, +127% click-to-install',
    summary: 'Blended micro-influencers and UGC creators on TikTok, then iterated the mix through a structured test-and-learn program to improve acquisition efficiency.',
    relevanceHook: 'Good proof for scaling creator programs beyond a single influencer model.',
    competitors: ['Fetch Rewards', 'Ibotta'],
    synonyms: [],
    story: "Rakuten needed a more scalable creator strategy on TikTok than pure influencer-only execution. We built a mix of micro-influencers and UGC creators, tested shopping categories and messaging angles, and scaled the content formats that consistently drove efficient installs and sign-ups. That structured iteration materially improved both CPI and click-to-install performance.",
  },
  {
    id: 43,
    client: 'Rakuten',
    year: 2025,
    market: 'US',
    title: 'Influencer Plus Paid Social Growth',
    industry: ['retail', 'e-commerce'],
    challenges: ['user acquisition'],
    channels: ['tiktok', 'influencers', 'paid social'],
    regions: ['americas'],
    outcomeTypes: ['scale & growth', 'cost efficiency'],
    tags: ['spark ads', 'shopping rewards', 'creator-led'],
    result: 'Met CPI and CPSU goals within 2 weeks, 80% sign-up CVR in Q4 2025',
    summary: 'Combined influencer-led TikTok content with paid amplification to turn Rakuten into a scalable acquisition program.',
    relevanceHook: 'Strong modern proof for creator-led paid social as a repeatable growth engine.',
    competitors: ['Fetch Rewards', 'Ibotta', 'Capital One Shopping'],
    synonyms: [],
    story: "Rakuten wanted TikTok to behave like a dependable acquisition engine, not a one-off experiment. We used creator-led content across shopping categories, then amplified the strongest assets through paid social to turn influence into efficient installs and sign-ups. The program hit efficiency goals quickly and grew into a broader evergreen growth model.",
  },
  {
    id: 44,
    client: 'Rakuten',
    year: 2025,
    market: 'US',
    title: 'TikTok One Creative Efficiency',
    industry: ['retail', 'e-commerce'],
    challenges: ['creative performance', 'improving efficiency'],
    channels: ['tiktok'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'creative effectiveness', 'test & learn'],
    tags: ['tiktok one', 'creator sourcing', 'essentials'],
    result: '+50% cost efficiency, -40% customer acquisition costs, 2x faster creative turnaround',
    summary: 'Used TikTok One creator sourcing and a faster test cycle to keep Rakuten’s creative pipeline aligned with platform pace.',
    relevanceHook: 'Useful proof for fixing creative production bottlenecks on TikTok.',
    competitors: [],
    synonyms: [],
    story: "Rakuten needed its video production speed to match TikTok’s testing cadence. We used TikTok One to source better-fit creators, tightened the turnaround cycle, and tested more relevant value propositions like essentials-led savings. That improved both creative throughput and acquisition efficiency.",
  },
  {
    id: 45,
    client: 'Rakuten',
    year: 2025,
    market: 'US',
    title: 'TikTok Smart Plus Efficiency',
    industry: ['retail', 'e-commerce'],
    challenges: ['improving efficiency'],
    channels: ['tiktok'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency'],
    tags: ['smart+', 'automation', 'spark ads', 'tiktok one'],
    result: '-10% CPI, -15% cost per subscribed user',
    summary: 'Tested TikTok Smart+ using existing Spark Ads and TikTok One assets to improve campaign efficiency without changing creative direction.',
    relevanceHook: 'Good proof for AI-assisted media optimization on TikTok.',
    competitors: [],
    synonyms: [],
    story: "Rakuten had already been refreshing creative, but costs stayed high. We tested TikTok Smart+ using a bank of existing Spark Ads and TikTok One videos, letting the platform optimize delivery automatically against efficiency goals. That helped bring both CPI and cost per subscribed user down.",
  },

  {
    id: 46,
    client: 'Local Now',
    year: 2022,
    market: 'US',
    title: 'Programmatic CTV Performance',
    industry: ['streaming', 'media'],
    challenges: ['user acquisition', 'brand awareness'],
    channels: ['programmatic', 'ctv'],
    regions: ['americas'],
    outcomeTypes: ['cost efficiency', 'audience strategy'],
    tags: ['the trade desk', 'roku oneview', 'vcr', 'cpm'],
    result: '-50% CPI, -17% CPM, +0.11% VCR',
    summary: 'Balanced programmatic CTV suppliers and KPIs to improve install efficiency without sacrificing video completion quality.',
    relevanceHook: 'Useful proof for managing dual KPI tradeoffs in CTV buying.',
    competitors: [],
    synonyms: [],
    story: "Local Now needed its CTV program to deliver both strong video quality signals and efficient installs at the same time. We balanced investment across suppliers like The Trade Desk and Roku OneView, using programmatic controls to manage frequency, scale, and optimization against both VCR and CPI. That tradeoff management helped cut CPI and CPM while slightly improving VCR.",
  },
]

export const filterGroups = {
  industry: ['audio', 'cpg', 'e-commerce', 'entertainment', 'family', 'fashion', 'finance', 'fitness', 'gaming', 'health & wellness', 'media', 'publishing', 'retail', 'saas', 'sports', 'streaming', 'ticketing'],
  challenge: ['brand awareness', 'brand repositioning', 'conversion improvement', 'creative performance', 'driving revenue', 'fixing measurement', 'fraud reduction', 'full-funnel growth', 'global launch', 'growing organic acquisition', 'improving efficiency', 'incrementality', 'measurement', 'measurement cleanup', 'retention', 'scaling reach', 'user acquisition'],
  channel: ['aso', 'audio', 'ctv', 'display', 'influencers', 'native', 'ott', 'paid search', 'paid social', 'podcast', 'programmatic', 'reddit', 'snapchat', 'tiktok', 'youtube'],
  region: ['americas', 'apac', 'emea'],
  outcomeType: ['audience strategy', 'channel expertise', 'cost efficiency', 'creative effectiveness', 'fraud & brand safety', 'measurement & attribution', 'scale & growth', 'test & learn'],
}
